#!/bin/bash
cmd=$1
options=$2

cmd_path="./$cmd.sh"

if [ -a $cmd_path ]; then
    $cmd_path $2
else
    echo "That command does not exist: $cmd"
    echo "-------------------USAGE----------------------"
    echo "legend: [required]{command} [optional]{name}"
    echo "./miteh use {latest|original|name_of_snapshot}"
    echo "./miteh copy {original|name_of_snapshot}"
    echo "./miteh ls"
    echo "./miteh clean"
    echo "----------------------------------------------"
fi
